const list_product = [
  {
    id: 3,
    masp: "#125",
    tensp: "iPhone 13",
    hinhanh: "/accset/img/Dienthoai/ip13.webp",
    trangthai: "Điện thoại",
    gia: "8.500.000",
  },
  {
    id: 4,
    masp: "#126",
    tensp: "iPhone 12 Pro",
    hinhanh: "/accset/img/Dienthoai/ip12.webp",
    trangthai: "Điện thoại",
    gia: "9.200.000",
  },
  {
    id: 5,
    masp: "#127",
    tensp: "iPhone SE",
    hinhanh: "/accset/img/Dienthoai/se.webp",
    trangthai: "Điện thoại",
    gia: "6.500.000",
  },
  {
    id: 6,
    masp: "#128",
    tensp: "iPhone 14",
    hinhanh: "/accset/img/Dienthoai/ip14.webp",
    trangthai: "Điện thoại",
    gia: "7.800.000",
  },
  {
    id: 7,
    masp: "#129",
    tensp: "iPhone XR",
    hinhanh: "/accset/img/Dienthoai/ipxr.webp",
    trangthai: "Điện thoại",
    gia: "5.000.000",
  },
  {
    id: 7,
    masp: "#1254",
    tensp: "iPhone 15",
    hinhanh: "/accset/img/Dienthoai/ip15.webp",
    trangthai: "Điện thoại",
    gia: "5.000.000",
    thongtin:""
  },
  {
    id: 7,
    masp: "#12945",
    tensp: "iPhone 8",
    hinhanh: "/accset/img/Dienthoai/ip8.webp",
    trangthai: "Điện thoại",
    gia: "5.000.000",
  },
  {
    id: 7,
    masp: "#12945",
    tensp: "iPhone X",
    hinhanh: "/accset/img/Dienthoai/ip x.webp",
    trangthai: "Điện thoại",
    gia: "5.000.000",
  },
  {
    id: 8,
    masp: "#130",
    tensp: "AirPods Pro",
    hinhanh: "/accset/img/tai nghe/air pro.webp",
    trangthai: "Tai nghe",
    gia: "2.500.000",
  },
  {
    id: 9,
    masp: "#131",
    tensp: "AirPods 2nd Gen",
    hinhanh: "/accset/img/tai nghe/air pro1.webp",
    trangthai: "Tai nghe",
    gia: "1.800.000",
  },
  {
    id: 10,
    masp: "#132",
    tensp: "AirPods Max",
    hinhanh: "/accset/img/tai nghe/air max 1.webp",
    trangthai: "Tai nghe",
    gia: "5.000.000",
  },
  {
    id: 11,
    masp: "#133",
    tensp: "AirPods 3rd Gen",
    hinhanh: "/accset/img/tai nghe/airpodd max.webp",
    trangthai: "Tai nghe",
    gia: "2.200.000",
  },

  {
    id: 13,
    masp: "#135",
    tensp: "Apple Watch Series 7",
    hinhanh: "/accset/img/appwatch/3.webp",
    trangthai: "Đồng hồ thông minh",
    gia: "9.000.000",
  },
  {
    id: 14,
    masp: "#136",
    tensp: "Apple Watch SE",
    hinhanh:
      "/accset/img/appwatch/GUEST_28e63099-0ead-4415-a442-9c69139d3867.webp",
    trangthai: "Đồng hồ thông minh",
    gia: "6.500.000",
  },
  {
    id: 15,
    masp: "#137",
    tensp: "Apple Watch Series 6",
    hinhanh:
      "/accset/img/appwatch/GUEST_a843b285-4980-4c95-946d-fec46edf9c62.webp",
    trangthai: "Đồng hồ thông minh",
    gia: "7.800.000",
  },
  {
    id: 16,
    masp: "#138",
    tensp: "Apple Watch Series 5",
    hinhanh: "/accset/img/appwatch/wt 2.webp",
    trangthai: "Đồng hồ thông minh",
    gia: "7.200.000",
  },
  {
    id: 17,
    masp: "#139",
    tensp: "Apple Watch Series 4",
    hinhanh: "/accset/img/appwatch/wt 3.webp",
    trangthai: "Đồng hồ thông minh",
    gia: "6.000.000",
  },
  {
    id: 18,
    masp: "#140",
    tensp: "iPad 8th Gen",
    hinhanh: "/accset/img/ipad/apple ipad.webp",
    trangthai: "iPad",
    gia: "7.000.000",
  },
  {
    id: 19,
    masp: "#141",
    tensp: "iPad Air 4th Gen",
    hinhanh: "/accset/img/ipad/ip air.webp",
    trangthai: "iPad",
    gia: "8.500.000",
  },
  {
    id: 20,
    masp: "#142",
    tensp: "iPad Mini 6th Gen",
    hinhanh: "/accset/img/ipad/ip mini.webp",
    trangthai: "iPad",
    gia: "6.200.000",
  },
  {
    id: 21,
    masp: "#143",
    tensp: "iPad Pro 11-inch",
    hinhanh: "/accset/img/ipad/ipad air 1.webp",
    trangthai: "iPad",
    gia: "10.800.000",
  },
  {
    id: 22,
    masp: "#144",
    tensp: "iPad Pro 12.9-inch",
    hinhanh: "/accset/img/ipad/ipad mini.webp",
    trangthai: "iPad",
    gia: "13.000.000",
  },
  {
    id: 23,
    masp: "#145",
    tensp: "iPad 10th Gen",
    hinhanh: "/accset/img/ipad/ipad pro.webp",
    trangthai: "iPad",
    gia: "8.000.000",
  },
  {
    id: 24,
    masp: "#146",
    tensp: "iPad Pro 12.9-inch 5th Gen",
    hinhanh: "/accset/img/ipad/ipad smart.webp",
    trangthai: "iPad",
    gia: "15.500.000",
  },
];
function list_productall() {
  if (localStorage.getItem("dataproduct") == null) {
    const list_product = [
      {
        id: 3,
        masp: "#125",
        tensp: "iPhone 13",
        hinhanh: "/accset/img/Dienthoai/ip13.webp",
        trangthai: "Điện thoại",
        gia: "8.500.000",
      },
      {
        id: 4,
        masp: "#126",
        tensp: "iPhone 12 Pro",
        hinhanh: "/accset/img/Dienthoai/ip12.webp",
        trangthai: "Điện thoại",
        gia: "9.200.000",
      },
      {
        id: 5,
        masp: "#127",
        tensp: "iPhone SE",
        hinhanh: "/accset/img/Dienthoai/se.webp",
        trangthai: "Điện thoại",
        gia: "6.500.000",
      },
      {
        id: 6,
        masp: "#128",
        tensp: "iPhone 14",
        hinhanh: "/accset/img/Dienthoai/ip14.webp",
        trangthai: "Điện thoại",
        gia: "7.800.000",
      },
      {
        id: 7,
        masp: "#129",
        tensp: "iPhone XR",
        hinhanh: "/accset/img/Dienthoai/ipxr.webp",
        trangthai: "Điện thoại",
        gia: "5.000.000",
      },
      {
        id: 7,
        masp: "#1254",
        tensp: "iPhone 15",
        hinhanh: "/accset/img/Dienthoai/ip15.webp",
        trangthai: "Điện thoại",
        gia: "5.000.000",
      },
      {
        id: 7,
        masp: "#12945",
        tensp: "iPhone 8",
        hinhanh: "/accset/img/Dienthoai/ip8.webp",
        trangthai: "Điện thoại",
        gia: "5.000.000",
      },
      {
        id: 7,
        masp: "#12945",
        tensp: "iPhone X",
        hinhanh: "/accset/img/Dienthoai/ip x.webp",
        trangthai: "Điện thoại",
        gia: "5.000.000",
      },
      {
        id: 8,
        masp: "#130",
        tensp: "AirPods Pro",
        hinhanh: "/accset/img/tai nghe/air pro.webp",
        trangthai: "Tai nghe",
        gia: "2.500.000",
      },
      {
        id: 9,
        masp: "#131",
        tensp: "AirPods 2nd Gen",
        hinhanh: "/accset/img/tai nghe/air pro1.webp",
        trangthai: "Tai nghe",
        gia: "1.800.000",
      },
      {
        id: 10,
        masp: "#132",
        tensp: "AirPods Max",
        hinhanh: "/accset/img/tai nghe/air max 1.webp",
        trangthai: "Tai nghe",
        gia: "5.000.000",
      },
      {
        id: 11,
        masp: "#133",
        tensp: "AirPods 3rd Gen",
        hinhanh: "/accset/img/tai nghe/airpodd max.webp",
        trangthai: "Tai nghe",
        gia: "2.200.000",
      },

      {
        id: 13,
        masp: "#135",
        tensp: "Apple Watch Series 7",
        hinhanh: "/accset/img/appwatch/3.webp",
        trangthai: "Đồng hồ thông minh",
        gia: "9.000.000",
      },
      {
        id: 14,
        masp: "#136",
        tensp: "Apple Watch SE",
        hinhanh:
          "/accset/img/appwatch/GUEST_28e63099-0ead-4415-a442-9c69139d3867.webp",
        trangthai: "Đồng hồ thông minh",
        gia: "6.500.000",
      },
      {
        id: 15,
        masp: "#137",
        tensp: "Apple Watch Series 6",
        hinhanh:
          "/accset/img/appwatch/GUEST_a843b285-4980-4c95-946d-fec46edf9c62.webp",
        trangthai: "Đồng hồ thông minh",
        gia: "7.800.000",
      },
      {
        id: 16,
        masp: "#138",
        tensp: "Apple Watch Series 5",
        hinhanh: "/accset/img/appwatch/wt 2.webp",
        trangthai: "Đồng hồ thông minh",
        gia: "7.200.000",
      },
      {
        id: 17,
        masp: "#139",
        tensp: "Apple Watch Series 4",
        hinhanh: "/accset/img/appwatch/wt 3.webp",
        trangthai: "Đồng hồ thông minh",
        gia: "6.000.000",
      },
      {
        id: 18,
        masp: "#140",
        tensp: "iPad 8th Gen",
        hinhanh: "/accset/img/ipad/apple ipad.webp",
        trangthai: "iPad",
        gia: "7.000.000",
      },
      {
        id: 19,
        masp: "#141",
        tensp: "iPad Air 4th Gen",
        hinhanh: "/accset/img/ipad/ip air.webp",
        trangthai: "iPad",
        gia: "8.500.000",
      },
      {
        id: 20,
        masp: "#142",
        tensp: "iPad Mini 6th Gen",
        hinhanh: "/accset/img/ipad/ip mini.webp",
        trangthai: "iPad",
        gia: "6.200.000",
      },
      {
        id: 21,
        masp: "#143",
        tensp: "iPad Pro 11-inch",
        hinhanh: "/accset/img/ipad/ipad air 1.webp",
        trangthai: "iPad",
        gia: "10.800.000",
      },
      {
        id: 22,
        masp: "#144",
        tensp: "iPad Pro 12.9-inch",
        hinhanh: "/accset/img/ipad/ipad mini.webp",
        trangthai: "iPad",
        gia: "13.000.000",
      },
      {
        id: 23,
        masp: "#145",
        tensp: "iPad 10th Gen",
        hinhanh: "/accset/img/ipad/ipad pro.webp",
        trangthai: "iPad",
        gia: "8.000.000",
      },
      {
        id: 24,
        masp: "#146",
        tensp: "iPad Pro 12.9-inch 5th Gen",
        hinhanh: "/accset/img/ipad/ipad smart.webp",
        trangthai: "iPad",
        gia: "15.500.000",
      },
    ];

    localStorage.setItem("dataproduct", JSON.stringify(list_product));
  }
}

function user_admin() {
  if (localStorage.getItem("user_admin") == null) {
    const user_admin = {
      name: "Van Muoi",
      pass: "123456",
    };
    localStorage.setItem("user_admin", JSON.stringify(user_admin));
  }
}
list_productall();
user_admin();
